### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by baditaflorin** [OsmQc/mtl2osm#19]
python osm_grid_splitter.py mexico-latest.osm.pbf grid.geojson \home
Traceback (most recent call last):
  File "osm_grid_splitter.py", line 119, in <module>
    main()
  File "osm_grid_splitter.py", line 75, in main
    json_feature_index[feature['id']] = feature
KeyError: 'id'
mapuser@map-analyst:/data/files/florinb/github/mtl2osm/mtl2osm$ python osm_grid_splitter.py mexico-latest.osm.pbf grid.geojson /data/files/florinb/github/mtl2osm/mtl2osm/
Traceback (most recent call last):
  File "osm_grid_splitter.py", line 119, in <module>
    main()
  File "osm_grid_splitter.py", line 75, in main
    json_feature_index[feature['id']] = feature
KeyError: 'id'

**Comment by guillaumep** [comment]
Hello @baditaflorin , thanks for using osm_grid_splitter.py!

The program was conceived to work with OSM XML files, thus will not work with .pbf extracts.

Also, can you link to the grid.geojson file you are using? How did you generate the grid file? (In our case we used grid files generated using the HOT Tasking Manager)
